name: "unlock a broken state file"
on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: lock id to unlock
        required: true
        type: string
        default: ''
jobs:
  init:
    name: use terraform to unlock state
    runs-on: ubuntu-latest 
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::406663345920:role/ucsb-role-terraform-full
          aws-region: us-west-2
          role-duration-seconds: 900

      - name: checkout branch
        uses: actions/checkout@v3
          
      - name: install terraform
        uses: hashicorp/setup-terraform@v2

      - name: init terraform
        run: cd terraform/zones; terraform init -upgrade
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}        
    
      - name: unlock state file
        id: unlock
        run: cd terraform/zones; terraform force-unlock -force ${{ inputs.lock_id }}
