

name: "terraform: initialize and plan"
on:
  workflow_dispatch:
  push:
    branches:
      - '!main'
      - 'dev'
    paths:
      - '!.github/workflows/**'

    
jobs:

  init:
    name: "terraform: setup, initialize, and plan"
    runs-on: ubuntu-latest 
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::406663345920:role/ucsb-role-terraform-full
          aws-region: us-west-2
          role-duration-seconds: 900

      - name: checkout branch
        uses: actions/checkout@v3
          
      - name: "terraform: installing"
        uses: hashicorp/setup-terraform@v2

      - name: "terraform: init"
        run: cd terraform/zones; terraform init -upgrade
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}        
    
      - name: "terraform: plan stage"
        id: plan
        run: cd terraform/zones; terraform plan -no-color